### PR TITLE
fix(cicd): make failure slack message safer

### PR DESCRIPTION
**Pull request by roleyfoley**
- Enables integration testing on all changes 
- Moves docker compose project env to the environment section to make it global 
- Fixes slack message to make sure when it fails that it sends

### CODE REVIEW

**Comment by adamkerz** [comment]
retest

**Comment by adamkerz** [comment]
@roleyfoley How do I trigger re-running of the tests for this one?

**Comment by roleyfoley** [comment]
Click on the details and that will take you to jenkins. Then click the replay icon in the top right

just kicked it off.

**Comment by adamkerz** [comment]
This is breaking, but I don't think from this PR. Once finished with the shared db stuff, I'll look into it.

**Pull request merged**
