### PR TITLE
Adding architecture diagrams

### PR DESCRIPTION
**Pull request by adamkerz**

### CODE REVIEW

**Comment by adamkerz** [comment]
High level diagram isn't great to use in the doco purely because it gets scaled down. (So I didn't touch it.) Node <--> Channel interactions might be under-documented.

**Comment by monkeypants** [comment]
what do the colours mean?

**Review by monkeypants — APPROVED** [review]
happy to merge but what do the colours mean?

**Comment by adamkerz** [comment]
Dunno, they were your colours to start with in the top three diagrams. 😄 Perhaps signifying components that were complete vs. being worked on vs. being a figment of imagination? I only used colours to distinguish between different layers really.

**Pull request merged**
