### PR TITLE
Extract WebSub

### PR DESCRIPTION
**Pull request by magicjohnson**
Move all websub related views, UseCases and processors into separated repository

### CODE REVIEW

**Review by koriaf — APPROVED** [review]
looks fine to me. I'm don't understand fully the spitting between custom intergov logic and the generic websub yet, but probably there is some. we will see once it's working.

Initially I though that it would be nice just to make websub part with all callbacks and delivery components be moved out to a separate api, and the only way Intergov communicates with it is http requests; in this PR some code communication is done as well. So assuming the code communication is made only for us to be able to add custom delivery rules and things like that. In case of pure-http approach we will have to inherit the generic websub hub core, adding a layer of our own validators/etc and then just run it on per-setup basis.

**Comment by adamkerz** [comment]
@koriaf If we host a separate subscription API hub that handles subscriptions for a Node and for multiple Channels, then the Node and each Channel needs make a http call to publish. No problem there. BUUUT, the Hub then needs to know how to authenticate each Node User or Channel User for each type of subscription. This is something that the Node and Channel's already know how to do and may not always be simple - eg Etherium channel would look up participants on the smart contract.

The Hub would also need to validate that a message ID is valid - ie. you can't subscribe to a message that doesn't exist. The Node or Channel would also need to inform the Hub of that fact somehow. Similar validation is probably needed for a predicate pattern subscription.

So, splitting the code into a generic subscription library and making it simple for Channel and Node implementations to use this and add their validation and auth on top seems like the simpler and clearer way to me. If we do this, then code communication for publishing is also simpler.

**Comment by adamkerz** [comment]
Aaaaand I didn't look at the code before posting that comment. The comment still applies, but @magicjohnson I just had a long meeting with Chris where we hashed this out and I think we now need to pair on this as this PR wasn't my intention and isn't quite how we are currently thinking :-)

**Comment by monkeypants** [comment]
Do we have any updates on this @magicjohnson / @adamkerz ?

**Comment by magicjohnson** [comment]
This PR probably must be declined since we decided to go another way: put Subscription and Notification repos implementation into WebSub package and keep UseCases and endpoints within intergov. Common code is already shared within https://github.com/trustbridge/libtrustbridge (but still need to be included as dependency into intergov)

**Comment by monkeypants** [comment]
OK, thanks. Looking forward to the new PR.

**Pull request closed without merging**
