### PR TITLE
fix(demo): docker-compose.yml file is a link, not a text file

### PR DESCRIPTION
**Pull request by koriaf**
@adamkerz

### CODE REVIEW

**Comment by adamkerz** [comment]
Sorry, that's a Windows thing and I didn't realise it used to be a link. Better to avoid links TBH. Do we need it anyway - the pie tasks are pointing directly to `demo-dc.yml`?

**Comment by koriaf** [comment]
it just allows us to use `docker-compose` instead of `docker-compose -f demo-dc.yml` for any other custom command, which is less verbose. I think we may just rename `demo-dc.yml` to `docker-compose.yml` and update all references to it, given the demo is the main workflow for local developers and cloud devops uses other things anyway.

**Comment by monkeypants** [comment]
I think this is a convenience for linux people. Seems harmless to include it, except that it will break if we reorganise the docker-compose stuff.

**Comment by koriaf** [comment]
will re-created the PR

**Pull request closed without merging**
