### PR TITLE
feat(message_rx): Disable fat pings endpoint

### PR DESCRIPTION
**Pull request by koriaf**
@adamkerz @magicjohnson 

it's not a big PR but just pushing some local things before stopping working on the node core for some time

### CODE REVIEW

**Comment by adamkerz** [comment]
@magicjohnson merge this one unless you think it's going to make things harder for you.

**Comment by magicjohnson** [comment]
I would remove unused code right away. Or (if it's a temporary measure) at least put some comments about when the code can be reenabled again.

**Comment by koriaf** [comment]
I don't think this endpoint will ever be enabled agani, but some validation rules may be moved to the message api itself. I've already updated the endpoint so it accepts both incoming and outgoing messages (was developed for outgoing initially), but not sure if some of this code will be moving there or not.

**Comment by magicjohnson** [comment]
there is no reason to keep obsolete code, we have git history.

**Comment by monkeypants** [comment]
@magicjohnson what should we do here? merge or reject.

**Review by magicjohnson — CHANGES_REQUESTED** [review]
Let's remove commented out lines and skipped tests

**Comment by koriaf** [comment]
@magicjohnson could you please then do it in your PR? it's pointless for me how to spend time on these changes and then for you merging them to your work.

and then close this one

**Comment by adamkerz** [comment]
Is this OTBE or about to be, @magicjohnson?

**Comment by magicjohnson** [comment]
I believe we still need to remove those pieces of code, but I didn't get to this thing yet

**Pull request closed without merging**
